-- Drop all tables to start fresh
DROP TABLE IF EXISTS "ViewGrant" CASCADE;
DROP TABLE IF EXISTS "DocumentTag" CASCADE;
DROP TABLE IF EXISTS "Tag" CASCADE;
DROP TABLE IF EXISTS "DocumentPath" CASCADE;
DROP TABLE IF EXISTS "DocumentLink" CASCADE;
DROP TABLE IF EXISTS "DocumentHistory" CASCADE;
DROP TABLE IF EXISTS "StructuredDocument" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "Account" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TYPE IF EXISTS "UserRole" CASCADE;
