import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Bundled browser-extension output — lints its own source separately.
    "extensions/browser-bookmarks/browser-extension/dist/**",
    // Prisma-generated client code (regenerated by `prisma generate`).
    "lib/database/generated/**",
    // Local git worktree copies of the same repo.
    ".claude/worktrees/**",
    ".worktrees/**",
    // Playwright artifacts.
    "test-results/**",
    "playwright-report/**",
  ]),
]);

export default eslintConfig;
