// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (Next.js convention), then fall back to .env
config({ path: ".env.local" });
config(); // This loads .env as fallback

// For build time: use DATABASE_URL if available, otherwise use a dummy URL
// Prisma does not connect during build but it requires the URL format for validation
// Neon-Vercel integrationprovides the real DATABASE_URL at runtime.
const databaseUrl =
  process.env.DATABASE_URL ||
  "postgresql://dummy:dummy@localhost:5432/dummy?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
    // Shadow DB for `migrate dev` / `migrate diff --from-migrations`. Neon
    // can't create the throwaway shadow itself, so point this at a local
    // Postgres (e.g. the dev Docker container) via SHADOW_DATABASE_URL.
    // Unset in normal use (undefined = no effect).
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL,
  },
});
