/**
 * Generate the Block Catalog reference doc.
 *
 * Statically scans every `registerBlock()` call for its identity, description,
 * and (optional) `aiHint`, joins each to its AI authoring mode
 * (`lib/domain/blocks/ai-authoring`), and writes a reviewable markdown table to
 * `docs/notes-feature/guides/editor/BLOCK-CATALOG.md`.
 *
 * This is a *static* scan (not a runtime import) so it never boots the client
 * block runtime — drift-safe and safe to run anywhere.
 *
 *   pnpm blocks:catalog          # regenerate the doc
 *   pnpm blocks:catalog --check  # exit 1 if the committed doc is stale (CI)
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  getBlockAuthoringMode,
  isBlockAuthorable,
  type BlockAuthoringMode,
} from "../lib/domain/blocks/ai-authoring";

const ROOT = process.cwd();
const OUT = "docs/notes-feature/guides/editor/BLOCK-CATALOG.md";

interface RawBlock {
  type: string;
  label: string;
  description: string;
  aiHint?: string;
  family: string;
  group: string;
  file: string;
}

/** List block source files in a directory, tolerating a missing directory. */
function filesIn(dir: string, exts: string[]): string[] {
  try {
    return readdirSync(join(ROOT, dir))
      .filter((f) => exts.some((e) => f.endsWith(e)) && !f.includes(" 2."))
      .map((f) => `${dir}/${f}`);
  } catch {
    return [];
  }
}

const BLOCK_FILES = [
  ...filesIn("extensions/publishing/blocks", [".ts"]),
  ...filesIn("lib/domain/editor/extensions/blocks", [".ts", ".tsx"]),
  "extensions/calendar/editor/calendar-view-block.ts",
];

/** Extract each `registerBlock({ … })` argument object as a source substring. */
function extractRegisterObjects(src: string): string[] {
  const objs: string[] = [];
  let idx = 0;
  for (;;) {
    const start = src.indexOf("registerBlock({", idx);
    if (start === -1) break;
    let depth = 0;
    let i = start + "registerBlock(".length;
    const objStart = i;
    for (; i < src.length; i++) {
      const c = src[i];
      if (c === "{") depth++;
      else if (c === "}") {
        depth--;
        if (depth === 0) {
          i++;
          break;
        }
      }
    }
    objs.push(src.slice(objStart, i));
    idx = i;
  }
  return objs;
}

/** Read a top-level (2-space indented) string field from the object literal. */
function field(obj: string, key: string): string | undefined {
  const re = new RegExp(`\\n  ${key}:\\s*(["'\`])([\\s\\S]*?)\\1`);
  const m = obj.match(re);
  return m ? m[2].replace(/\s+/g, " ").trim() : undefined;
}

function collect(): { blocks: RawBlock[]; skipped: number } {
  const blocks: RawBlock[] = [];
  let skipped = 0;
  for (const file of BLOCK_FILES) {
    let src: string;
    try {
      src = readFileSync(join(ROOT, file), "utf8");
    } catch {
      continue;
    }
    for (const obj of extractRegisterObjects(src)) {
      const type = field(obj, "type");
      // Blocks whose `type` is a constant (e.g. unsupportedBlock) can't be read
      // statically; they are the never-authorable placeholders, so skip them.
      if (!type) {
        skipped++;
        continue;
      }
      blocks.push({
        type,
        label: field(obj, "label") ?? type,
        description: field(obj, "description") ?? "",
        aiHint: field(obj, "aiHint"),
        family: field(obj, "family") ?? "?",
        group: field(obj, "group") ?? "?",
        file,
      });
    }
  }
  blocks.sort((a, b) =>
    `${a.family}${a.group}${a.type}`.localeCompare(`${b.family}${b.group}${b.type}`)
  );
  return { blocks, skipped };
}

const MODE_LABEL: Record<BlockAuthoringMode, string> = {
  full: "full",
  container: "container",
  seed: "seed",
  reference: "reference",
  computed: "computed",
  deferred: "⏸ deferred",
};

function esc(s: string): string {
  return s.replace(/\|/g, "\\|");
}

function render(blocks: RawBlock[], skipped: number): string {
  const authorable = blocks.filter((b) => isBlockAuthorable(b.type));
  const deferred = blocks.filter((b) => !isBlockAuthorable(b.type));
  const calibrated = blocks.filter((b) => b.aiHint).length;

  const lines: string[] = [];
  lines.push("<!-- GENERATED by scripts/generate-block-catalog.ts — do not edit by hand. -->");
  lines.push("<!-- Calibrate the AI-facing text by editing each block's `aiHint` in its registerBlock() call, then run `pnpm blocks:catalog`. -->");
  lines.push("");
  lines.push("# Block Catalog — AI Authoring");
  lines.push("");
  lines.push(
    "Every registered block, the description a model sees when authoring it, and the **authoring mode** that governs how the AI may create it. The model-facing text is the block's `aiHint` when present (✎), otherwise its human tooltip `description`."
  );
  lines.push("");
  lines.push(
    `**${blocks.length}** registered · **${authorable.length}** authorable · **${deferred.length}** deferred · **${calibrated}** calibrated with an aiHint${skipped ? ` · ${skipped} non-literal-type placeholder(s) skipped` : ""}.`
  );
  lines.push("");
  lines.push("**Authoring modes** — `full` (model writes all attrs) · `container` (full + nested child blocks, Phase 2) · `seed` (inserted empty; payload supplied later) · `reference` (points at existing content) · `computed` (config only; block derives content) · `⏸ deferred` (needs a bespoke tool; not yet authorable). Policy lives in [`lib/domain/blocks/ai-authoring.ts`](../../../../lib/domain/blocks/ai-authoring.ts).");
  lines.push("");

  for (const family of ["content", "layout", "form"]) {
    const rows = blocks.filter((b) => b.family === family);
    if (!rows.length) continue;
    lines.push(`## ${family[0].toUpperCase()}${family.slice(1)}`);
    lines.push("");
    lines.push("| Block | Mode | AI-facing description | Source |");
    lines.push("| --- | --- | --- | --- |");
    for (const b of rows) {
      const mode = MODE_LABEL[getBlockAuthoringMode(b.type)];
      const text = (b.aiHint ? `✎ ${b.aiHint}` : b.description) || "—";
      lines.push(
        `| \`${b.type}\` | ${mode} | ${esc(text)} | \`${b.file.split("/").pop()}\` |`
      );
    }
    lines.push("");
  }

  return lines.join("\n") + "\n";
}

function main(): void {
  const check = process.argv.includes("--check");
  const { blocks, skipped } = collect();
  const output = render(blocks, skipped);

  if (check) {
    let current = "";
    try {
      current = readFileSync(join(ROOT, OUT), "utf8");
    } catch {
      /* missing file counts as stale */
    }
    if (current !== output) {
      console.error(
        `✗ ${OUT} is stale. Run \`pnpm blocks:catalog\` and commit the result.`
      );
      process.exit(1);
    }
    console.log(`✓ ${OUT} is up to date (${blocks.length} blocks).`);
    return;
  }

  writeFileSync(join(ROOT, OUT), output);
  console.log(`✓ wrote ${OUT} — ${blocks.length} blocks (${skipped} skipped).`);
}

main();
